# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HeyweekCli < Formula
  desc "Heyweek CLI"
  homepage "https://heyweek.com"
  version "1.1.15"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/marvinhosea/homebrew-heyweek-cli/releases/download/v1.1.15/Heyweek_v1.1.15_macOS_amd64.zip", using: CurlDownloadStrategy
    sha256 "b6c34558389c0c1b7e8b313d780f5564164aebd8ea35e64b1f1ce7596168686d"

    def install
      bin.install "hw"
      rm Dir["#{bin}/{hw-completion.bash,hw-completion.zsh}"]
      system bin/"hw", "completion", "--shell", "bash"
      system bin/"hw", "completion", "--shell", "zsh"
      bash_completion.install "hw-completion.bash"
      zsh_completion.install "hw-completion.zsh"
      (zsh_completion/"_hw").write <<~EOS
        #compdef hw
        _hw () {
          local e
          e=$(dirname ${funcsourcetrace[1]%:*})/hw-completion.zsh
          if [[ -f $e ]]; then source $e; fi
        }
      EOS
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/marvinhosea/homebrew-heyweek-cli/releases/download/v1.1.15/Heyweek_v1.1.15_macOS_arm64.zip", using: CurlDownloadStrategy
    sha256 "fa15c21ced7399a145e6af324511e1c5251172defe1ac45509f9155b17820814"

    def install
      bin.install "hw"
      rm Dir["#{bin}/{hw-completion.bash,hw-completion.zsh}"]
      system bin/"hw", "completion", "--shell", "bash"
      system bin/"hw", "completion", "--shell", "zsh"
      bash_completion.install "hw-completion.bash"
      zsh_completion.install "hw-completion.zsh"
      (zsh_completion/"_hw").write <<~EOS
        #compdef hw
        _hw () {
          local e
          e=$(dirname ${funcsourcetrace[1]%:*})/hw-completion.zsh
          if [[ -f $e ]]; then source $e; fi
        }
      EOS
    end
  end

  def caveats
    <<~EOS
      ❤ Thanks for installing the Heyweek CLI! To get started run `hw auth login` first.
    EOS
  end
end
