# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HeyweekCli < Formula
  desc "Heyweek CLI"
  homepage "https://heyweek.com"
  version "1.1.11"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/marvinhosea/heyweek-cli/releases/download/v1.1.11/Heyweek_v1.1.11_macOS_amd64.zip", using: CurlDownloadStrategy
    sha256 "f305fb47b5070e71ab308ac011345d92538449f5a9e258aa80326b3397932c0f"

    def install
      bin.install "hw"
      rm Dir["#{bin}/{hw-completion.bash,hw-completion.zsh}"]
      system bin/"hw", "completion", "--shell", "bash"
      system bin/"hw", "completion", "--shell", "zsh"
      bash_completion.install "hw-completion.bash"
      zsh_completion.install "hw-completion.zsh"
      (zsh_completion/"_hw").write <<~EOS
        #compdef hw
        _hw () {
          local e
          e=$(dirname ${funcsourcetrace[1]%:*})/hw-completion.zsh
          if [[ -f $e ]]; then source $e; fi
        }
      EOS
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/marvinhosea/heyweek-cli/releases/download/v1.1.11/Heyweek_v1.1.11_macOS_arm64.zip", using: CurlDownloadStrategy
    sha256 "1351b01c7fb1862d97e568375844b4f9a96ea356b147d22358934953a9afcda7"

    def install
      bin.install "hw"
      rm Dir["#{bin}/{hw-completion.bash,hw-completion.zsh}"]
      system bin/"hw", "completion", "--shell", "bash"
      system bin/"hw", "completion", "--shell", "zsh"
      bash_completion.install "hw-completion.bash"
      zsh_completion.install "hw-completion.zsh"
      (zsh_completion/"_hw").write <<~EOS
        #compdef hw
        _hw () {
          local e
          e=$(dirname ${funcsourcetrace[1]%:*})/hw-completion.zsh
          if [[ -f $e ]]; then source $e; fi
        }
      EOS
    end
  end

  def caveats
    <<~EOS
      ❤ Thanks for installing the Heyweek CLI! To get started run `hw auth login` first.
    EOS
  end
end
