# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HeyweekCli < Formula
  desc "Heyweek CLI"
  homepage "https://heyweek.com"
  version "1.1.13"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/marvinhosea/homebrew-heyweek-cli/releases/download/v1.1.13/Heyweek_v1.1.13_macOS_amd64.zip", using: CurlDownloadStrategy
    sha256 "194d7a3dc3631b502d573e491cf2ec5d6e4eb91d6cef67bb2fbcc58f7f3c8dce"

    def install
      bin.install "hw"
      rm Dir["#{bin}/{hw-completion.bash,hw-completion.zsh}"]
      system bin/"hw", "completion", "--shell", "bash"
      system bin/"hw", "completion", "--shell", "zsh"
      bash_completion.install "hw-completion.bash"
      zsh_completion.install "hw-completion.zsh"
      (zsh_completion/"_hw").write <<~EOS
        #compdef hw
        _hw () {
          local e
          e=$(dirname ${funcsourcetrace[1]%:*})/hw-completion.zsh
          if [[ -f $e ]]; then source $e; fi
        }
      EOS
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/marvinhosea/homebrew-heyweek-cli/releases/download/v1.1.13/Heyweek_v1.1.13_macOS_arm64.zip", using: CurlDownloadStrategy
    sha256 "cee97b97def2313bc3a65ac6b216f7e07896571d0ddadcf377afbe4dc5f92dad"

    def install
      bin.install "hw"
      rm Dir["#{bin}/{hw-completion.bash,hw-completion.zsh}"]
      system bin/"hw", "completion", "--shell", "bash"
      system bin/"hw", "completion", "--shell", "zsh"
      bash_completion.install "hw-completion.bash"
      zsh_completion.install "hw-completion.zsh"
      (zsh_completion/"_hw").write <<~EOS
        #compdef hw
        _hw () {
          local e
          e=$(dirname ${funcsourcetrace[1]%:*})/hw-completion.zsh
          if [[ -f $e ]]; then source $e; fi
        }
      EOS
    end
  end

  def caveats
    <<~EOS
      ❤ Thanks for installing the Heyweek CLI! To get started run `hw auth login` first.
    EOS
  end
end
