# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HeyweekCli < Formula
  desc "Heyweek CLI"
  homepage "https://heyweek.com"
  version "1.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marvinhosea/heyweek-cli/releases/download/v1.0.7/Heyweek_1.0.7_macOS_amd64.zip", using: CurlDownloadStrategy
      sha256 "76f76de0d2faa754d240b3d34da366ca31ceb17237b08773dbcc22c8a648b27b"

      def install
        bin.install "bin/hw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marvinhosea/heyweek-cli/releases/download/v1.0.7/Heyweek_1.0.7_macOS_arm64.zip", using: CurlDownloadStrategy
      sha256 "c9f7cf115fd32374e9b1ed25fd9240ea8e28b8a5547d36face73f8c8dbc47f62"

      def install
        bin.install "bin/hw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marvinhosea/heyweek-cli/releases/download/v1.0.7/Heyweek_1.0.7_linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "6688f5c5cfa0554d549c39c38b33a6ed9d2ece7bca7c18d5ad5610076cab0659"

        def install
          bin.install "bin/hw"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marvinhosea/heyweek-cli/releases/download/v1.0.7/Heyweek_1.0.7_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "a1d93aa84d9870f8533c2bda53601f21c61fd7a74ee2e3988adb12a9b58ff3ad"

        def install
          bin.install "bin/hw"
        end
      end
    end
  end
end
